#!/usr/bin/env node
/* -*- mode: Javascript -*- */
var log = console.log;

var malloc =
    function(x,y) {
	var mem = [];
	for (i=0; i < y; i++)
	{
	    var raw = '';
	    for (j=0; j < x; j++)
	    {
		raw += ' ';
	    }

	    mem.push(raw);
	}

	return mem;
    };

var print_iso_at =
    function(x, what, out) {
	for (i=0; i<what.length; i++) {
	    var c = what[i];
	    var ii = i + x;
	    var line = out[i];

	    if (line) {
		line = line.slice(0,ii) + c + line.slice(ii+1);
		out[i] = line;
	    }
	}
    };

var POS = 0;
var SPACING = 4;

var the_matrix = malloc(225, 100);

process.stdin.resume();
process.stdin.setEncoding('utf8');

process.stdin.on('data', function (d) {
    var dd = d.split('\n');

    for (var k in dd) {
	print_iso_at(POS, dd[k], the_matrix);
	POS += SPACING;
    }
});
       
process.stdin.on('end', function () {
    for (var line in the_matrix)
    {
	var l = the_matrix[line];
	if (l.trim())
	    console.log(l);
    }
});